name = "fp2"
version = "0.0.1"

licences = ["Apache-2.0"]
description = "A porting of some parts of fp-ts to Gleam"
repository = { type = "github", user = "lucasavila00", repo = "fp2" }

[dependencies]
gleam_stdlib = "~> 0.22"
gleam_json = "~> 0.5"

[dev-dependencies]
gleeunit = "~> 0.6"
